// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwY7SHxzhC-7uNOIb7un3uJ2hl_1TrRvI',
    appId: '1:126146501871:web:96445664f8f46307ec8f1a',
    messagingSenderId: '126146501871',
    projectId: 'shopbar-b2270',
    authDomain: 'shopbar-b2270.firebaseapp.com',
    storageBucket: 'shopbar-b2270.firebasestorage.app',
    measurementId: 'G-CW9VBYZ6LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNQfllJatjxsR0QklUul_tYNKPuPeat1A',
    appId: '1:126146501871:android:195f79ff6b0f4a43ec8f1a',
    messagingSenderId: '126146501871',
    projectId: 'shopbar-b2270',
    storageBucket: 'shopbar-b2270.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKEPsXn_lR68eKV8-m4ETGu-s_PhbtzEU',
    appId: '1:126146501871:ios:ec5fdb1ccb9cda2dec8f1a',
    messagingSenderId: '126146501871',
    projectId: 'shopbar-b2270',
    storageBucket: 'shopbar-b2270.firebasestorage.app',
    iosBundleId: 'com.example.shopbar',
  );
}
